### PR TITLE
Add type safe enable, diasble and has.

### PR DESCRIPTION
**Pull request by maxbla**
This commit adds traits Enableable and Disableable which replace the
dynamic typing previously used for `enable`, `disable` and `has` methods on
DeviceWrapper.

This fixes the last item in #42

There are two unresolved issue with this PR. It adds separate `Enableable` and `Disableable` traits. Those have pretty bad names, so probably need new ones. Second, the reason I needed two traits instead of one is that this library appears not to have a binding to `libevdev_disable_property` That function was added with libevdev version 1.10, [relaesed October 2020](https://lists.freedesktop.org/archives/input-tools/2020-October/001545.html). If we create such a binding, this library no longer supports older versions of libevdev, but if we don't, we are bound to arcane API restrictions of old versions of libevdev. My preferred option is to wait until Debian Bullseye is released to merge this PR, with only one trait. I don't know when that will happen, but [libevdev 1.11 will be in that release](https://packages.debian.org/bullseye/libevdev-dev) and they [just did a "hard freeze" of packages a week ago](https://release.debian.org/), so probably not more than a couple of months off.

### CODE REVIEW

**Comment by maxbla** [comment]
Debian 11 was just released with libevdev 1.11, so I need to merge `Enableable` and `Disableable` into one trait before marking this ready for review.

**Comment by ndesh26** [comment]
I am wondering what should be the best course of action in such a case. Merging this patch will break evdev-rs on versions earlier than Debian 11.  One option is always building from scratch and not relying on the package that is already installed on the system. However, I am worried that it could lead to other complications in the system due to a version mismatch. 

I looked up other libraries for inspiration and it seems that there is an ongoing discussion on this [topic](https://github.com/rust-lang/git2-rs/issues/721).

**Comment by maxbla** [comment]
The option alex crichton proposed in that thread seems good to me. Have a `1.10` feature that is disabled by default. In build.rs we detect the version. If the version is past 1.10, we add the disable method. After a few years, 1.10 gets enabled by default then after more years the feature is removed and assumed to be always present. This obviously has complexity overhead, but I think I like the tradeoff. If you think this would work, I can implement it with this PR

**Comment by ndesh26** [comment]
I like the approach of adding a feature to handle this. How are you planning to handle the evdev-rs side of code? Are you planning to have two different traits for now?

**Comment by maxbla** [comment]
I don't like the idea of using two traits, as that is just setting ourselves up for a breaking change in the future, when we want to combine them. Having two is also more complicated, and it isn't clear to an end user why two traits would need to exist. I think we should just have an `Enable` trait and if the 1.10 feature is disabled, `InputProp` will not implement that trait. Enable/Disable on properties isn't that useful in my experience anyhow, since properties are not often critical to the function of a device (window managers don't use PROP_POINTER to identify mice for example). But users can always use the property specific methods `device.enable_property()` etc.

**Comment by ndesh26** [comment]
That sounds good to me. Let's go with that.

**Comment by maxbla** [comment]
I ended up making a minor modification to how this works in the most recent commit. Instead of automatically enabling the feature, build.rs now panics if the feature is enabled and libevdev is too old. This is better because downstream applications need to know whether a feature is enabled, not rely on some autodetection.

**Comment by ndesh26** [comment]
I haven't been able to spend time on this due to work commitments. Let's get it merged soon. I'll try to review it over the weekend. Thanks for being patient.

**Pull request merged**
