### PR TITLE
feat: add uinput and add some helpful impl methods

### PR DESCRIPTION
**Pull request by acheronfail**
Okay, sorry for the noise, but this PR supersedes PRs #14 and #15 (if this is merged then we can close those).

First of all - thanks for this crate! I've found it really useful so far. :smile: 

This PR makes adds the `libevdev_uinput` functions, and has some other changes:

**evdev-sys**

* Add `libevdev_uinput` functions:
    - `libevdev_uinput_create_from_device`
    - `libevdev_uinput_destroy`
    - `libevdev_uinput_get_devnode`
    - `libevdev_uinput_get_fd`
    - `libevdev_uinput_get_syspath`
    - `libevdev_uinput_write_event`
* Add `LIBEVDEV_UINPUT_OPEN_MANAGED` const
* Remove `raw::input_event`, `raw::timeval` and `raw::input_absinfo` and replace them with their `libc` equivalents
    - This makes this crate a little easier to use with other crates, or just with `libc` in general (and prevents duplication of code)

**evdev-rs**

* Add new `UInputDevice` opaque struct (similar to the existing `Device` struct)
    - `UInputDevice::create_from_device()`
    - `UInputDevice.fd()`
    - `UInputDevice.devnode()`
    - `UInputDevice.syspath()`
    - `UInputDevice.write_event()`
* Adds `InputEvent.as_raw() -> libc::input_event`
* Adds `InputEvent.from_raw() -> InputEvent`
* Adds `TimeVal.as_raw() -> libc::timeval`
* Fixes `Device.enable_event_code()` (see #14 for context)

### CODE REVIEW

**Comment by ndesh26** [comment]
Good to know that the crate is useful to you!! :smiley: 

I had a brief look and the code looks good to me. It would be great if you can split your patch into smaller patches and add the information about each change that you make in the commit mesage as you have added in this PR. 

Its good to have the reason for the change in the commit message itself. I was not able to follow it for some previous pull request, but would like to do it from now onwards.

Thanks

**Comment by acheronfail** [comment]
I've split the commit into three smaller commits, each with a more accurate description of the changes they include.

Let me know if you'd like any other changes :smile:

**Comment by ndesh26** [comment]
I had a look at the changes that you made. The code looks good now, but here are some things that you can improve upon:

- Each of the commits that you have should build successfully. This is helpful when doing a git bisect. 
- Make each commit as modular as possible, you have done good work in terms of the separation but I would have split the second commit into two, first which adds the changes in evdev-sys and other which uses those changes in evdev-rs.

I really appreciate that you have followed the coding style of repo in all the places. I wanted to add the feature of uinput since a long time. Thanks for your effort. I will be releasing a new version of evdev-rs soon after I merge your pull request.

**Comment by acheronfail** [comment]
Those are totally valid requests! I admit had just split the previous commit into smaller commits without checking if they built each time.

Now, each commit will build successfully, and the patches should each be specific too.

:slightly_smiling_face:

**Comment by acheronfail** [comment]
I've just noticed a mistake in the most recent commit, I'll fix that then this should be good to go :+1:

**Comment by acheronfail** [comment]
Okay, everything should be good to go now. All the commits build, and I've fixed up the extra context in each commit message.

**Comment by ndesh26** [comment]
Great!! Reviewing them now.

**Comment by ndesh26** [comment]
Took me a while to go through the code :sweat_smile:  

I have some minor modifications that I have made to the code. But I am not sure how I should be updating your pull request. Should I push to the branch that you created for this pull request?

**Comment by acheronfail** [comment]
Yep! Go ahead and push straight to my branch. 😊

**Comment by ndesh26** [comment]
I have pushed the changes. Please have a look and if you don't have any objections then I will merge the changes.

**Comment by acheronfail** [comment]
Looks good to me mate! Merge away :+1:

**Comment by ndesh26** [comment]
Thanks for the effort!!

**Pull request merged**
