### PR TITLE
Add virtual mouse example

### LINKED ISSUE #75: How to create a UInputDevice
howdy, thanks for making a neat crate! i've got reading events working nicely, but, i'm trying to work out exactly how to create a `UInputDevice` and am not sure how this is achievable with the `0.5.0` API? (likely relates to #42)

it seems the only way to create a `UInputDevice` is from an existing `Device` or `UninitDevice`, leading to a few possible options:
- creating an `UninitDevice` instance and passing this to `create_from_device` causes an `Error: Invalid argument (os error 22)`
- opening `/dev/uinput` (with `O_WRONLY` and `O_NONBLOCK`) then passing this to `Device::new_from_file` causes the same
- if you do have an existing device to clone, you can call `create_from_device` to create a `UInputDevice`, however, as this doesn't implement `WrapDevice` you don't seem to be able to change the configuration on this?

i'm probably missing something but, if you have any guidance on how to create and use a `UInputDevice` that'd be super helpful ^_^

cheers,

ryan

### PR DESCRIPTION
**Pull request by ryankurte**
I had another go with fresh eyes and worked out how to create a virtual mouse, and figured y'all might be interested in adding an example to the repo?

Resolves #75

### CODE REVIEW

**Comment by ndesh26** [comment]
It's great that you were able to work it out!

I would really love to add in more documentation and examples for future users. The example that you added requires adding additional crates which are don't seem too necessary for example itself.

Can you modify it so that it doesn't depend on those crate?

**Comment by ryankurte** [comment]
they're included as `dev-dependencies` so have no impact on consumers, but make it more straightforward to interact with / use the example. `std::io::Error` implements `std::Error` so it should be easy to remove `anyhow`, but `structopt` provides nice help and error messages compared to just grabbing the first argument / would be difficult to replicate.

**Comment by ndesh26** [comment]
I understand your concern but I would like to avoid using third party crates if I can. We have a basic cmdline argument handling in `examples/evtest.rs` as well.

**Comment by ndesh26** [comment]
Thanks for updating the example! I think it is ready to merge. The CI is failing due to code formatting. Please use `cargo fmt` to fix the formatting.

**Pull request merged**
